### ISSUE TITLE
API limit

### ISSUE THREAD

**Issue by dev-allinappli** [CiviMRF/synchronizing-civicrm-data-to-custom-posts#2]
Is the output limited to 25 result like in the API?
How to add the options('limit' =0) in the extension?

**Comment by kainuk** [comment]
https://github.com/CiviMRF/synchronizing-civicrm-data-to-custom-posts/pull/3 addresses this problem

**Comment by dev-allinappli** [comment]
Good to know. Thanks. Are you publishing a new version or should we patch?

**Comment by kainuk** [comment]
Hi, @allinappli we published a new version.
